version: '3.8'
services:
  frontend:
    build:
      context: ./Ayurhit_frontend
      dockerfile: Dockerfile
    container_name: ayurhit_frontend
    ports:
      - "80:80"
    networks:
      - backend

  backend:
    build:
      context: ./Ayurhit_backend
      dockerfile: Dockerfile
    container_name: ayurhit_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/ayurhit_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: manager
      SECRET_KEY: MyAyurhit-Hospital-Management-System-PGDAC-MARCH2024-FINALPROJECT
      EXP_TIMEOUT: 86400000
      APP_CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:7070
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      - backend

  mysqldb:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: manager
      MYSQL_DATABASE: ayurhit_db
    ports:
      - "3307:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
