FROM openjdk:11-jre-slim

WORKDIR /Ayurhit_Backend

COPY ./target/Ayurhit_Backend-0.0.1.jar /Ayurhit_Backend/Ayurhit_Backend.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/Ayurhit_Backend/Ayurhit_Backend.jar"]
